fun main(){
    print("Student Enrollment no. :")
    val erno= readln()
    print("Student Name :")
    val name= readln()
    print("Student Branch :")
    val branch= readln()
    print("Student Class :")
    val cls= readln()
    print("Student Batch :")
    val batch= readln()
    print("Student College Name :")
    val clg= readln()
    print("Student University Name :")
    val uni= readln()
    print("Student Age :")
    val age= readln()
    println()
    println("*******************************")
    println("Student Data : ")
    println("Enrollment No. : $erno")
    println("Name : $name")
    println("Age : $age")
    println("Branch : $branch")
    println("Class : $cls")
    println("Batch : $batch")
    println("College Name : $clg")
    println("University Name : $uni")
}